name: Tests

on:
  pull_request:

jobs:
  ubuntu-action-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm run cucumber || true
      - uses: ./
        with:
          name: "send cucumber report"
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/cucumber-report.json"
